RecipeFormatVersion: '2020-01-25'
ComponentName: com.alco.pub
ComponentVersion: NEXT_PATCH
ComponentDescription: A component that publishes temperature data to AWS IoT Core
ComponentPublisher: thineikhaing
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.alco.pub:mqttproxy:1:
          policyDescription: Allows access to publish to the temperature topic.
          operations:
          - aws.greengrass#PublishToTopic
          resources:
          - '*'
Manifests:
- Platform:
    os: all
  Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.alco.pub.zip
    Unarchive: ZIP
  Lifecycle:
    Run: python3 -u {artifacts:decompressedPath}/com.alco.pub/main.py
