RecipeFormatVersion: "2020-01-25"
ComponentName: "com.alco.sub"
ComponentVersion: "1.0.0"
ComponentDescription: "A component that subscribes to temperature data from AWS IoT Core"
ComponentPublisher: "thineikhaing"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        'com.alco.sub:mqttproxy:1':
          policyDescription: Allows access to subscribe to the temperature topic.
          operations:
            - aws.greengrass#SubscribeToIoTCore
          resources:
            - '*'
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://greengrass-component-artifacts-654654435122/com.alco.sub/1.0.1/com.alco.sub.zip"  # Replace with your actual S3 bucket name and component version
        Unarchive: ZIP
    Lifecycle:
      Run: "python3 -u {artifacts:decompressedPath}/com.alco.sub/main.py"
